# Form implementation generated from reading ui file 'd:\projects\nextgenmap\raw-res\vuln_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VulnsDialog(object):
    def setupUi(self, VulnsDialog):
        VulnsDialog.setObjectName("VulnsDialog")
        VulnsDialog.resize(824, 466)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VulnsDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vuln_tabs = QtWidgets.QTabWidget(parent=VulnsDialog)
        self.vuln_tabs.setObjectName("vuln_tabs")
        self.output_tab = QtWidgets.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.output_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.output_list = QtWidgets.QListWidget(parent=self.output_tab)
        self.output_list.setObjectName("output_list")
        self.verticalLayout_2.addWidget(self.output_list)
        self.vuln_tabs.addTab(self.output_tab, "")
        self.help_tab = QtWidgets.QWidget()
        self.help_tab.setObjectName("help_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.help_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.help_text = QtWidgets.QTextEdit(parent=self.help_tab)
        self.help_text.setObjectName("help_text")
        self.verticalLayout.addWidget(self.help_text)
        self.vuln_tabs.addTab(self.help_tab, "")
        self.horizontalLayout.addWidget(self.vuln_tabs)
        self.default_buttons = QtWidgets.QDialogButtonBox(parent=VulnsDialog)
        self.default_buttons.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.default_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.default_buttons.setObjectName("default_buttons")
        self.horizontalLayout.addWidget(self.default_buttons)

        self.retranslateUi(VulnsDialog)
        self.vuln_tabs.setCurrentIndex(0)
        self.default_buttons.accepted.connect(VulnsDialog.accept) # type: ignore
        self.default_buttons.rejected.connect(VulnsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VulnsDialog)

    def retranslateUi(self, VulnsDialog):
        _translate = QtCore.QCoreApplication.translate
        VulnsDialog.setWindowTitle(_translate("VulnsDialog", "Script Output"))
        self.vuln_tabs.setTabText(self.vuln_tabs.indexOf(self.output_tab), _translate("VulnsDialog", "Output"))
        self.vuln_tabs.setTabText(self.vuln_tabs.indexOf(self.help_tab), _translate("VulnsDialog", "Help"))
